### ISSUE TITLE
Update the New Repo with PRs

### ISSUE THREAD

**Issue by Ishaan28malik** [Ishaan28malik/Hacktoberfest-2024#1202]
## A new repo has been created and need some contributions in that repo 

Kindly start contributing [Here](https://github.com/Ishaan28malik/Get-Dev-Resources)

**Comment by Mehrapi** [comment]
I have sent a PR for this ,please, let me know if you have trouble accessing it. Thank you.

**Comment by GoGi2712** [comment]
Done!!😊

**Comment by lio2011** [comment]
Did some changes in that repo

**Comment by manas-init** [comment]
Created a PR for adding a script to print tree of directory. https://github.com/Ishaan28malik/Get-Dev-Resources/pull/100

**Comment by manas-init** [comment]
https://github.com/Ishaan28malik/Hacktoberfest-2020/pull/1524
