### ISSUE TITLE
Ineligible repository for Hacktoberfest

### ISSUE THREAD

**Issue by Goku-kun** [Ishaan28malik/Hacktoberfest-2024#1291]
After submitting the PR, I checked my hacktoberfest profile which showed me that this repository is an ineligible repository. I'm not sure what's wrong here because as per the rules of hacktoberfest, maintainers of the repository have to add "hacktoberfest" as a topic which is clearly mentioned in this repository and yet the issue pertains. Kindly take a look at it.

**Comment by thesumitdixit** [comment]
I also having the same issue

**Comment by codingsenpi** [comment]
same problem
