### ISSUE TITLE
0-1 Knapsack Problem in java. Hacktoberfest 2020

### ISSUE THREAD

**Issue by gourabk121** [Ishaan28malik/Hacktoberfest-2024#1533]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gourabk121** [comment]
Can I work on it?

**Comment by Blackwatch1910** [comment]
I have a working code on this one as one of my leetcode submission.
