### ISSUE TITLE
Add Kadane's Algorithm in Java

### ISSUE THREAD

**Issue by blindaks** [Ishaan28malik/Hacktoberfest-2024#1913]
Kadane's algorithm is a dynamic programming approach used to solve the maximum subarray problem, which involves finding the contiguous subarray with the maximum sum in an array of numbers.

**Comment by blindaks** [comment]
Please assign this issue to me under Hacktoberfest.

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.

**Comment by Anuj0918** [comment]
Hello sir . I want to work under this issue regarding kadane algorithm that is used for finding maximum subarray sum . I have good knowledge of data structures and working on this issue will further enhance my problem solving skills.please assigned it to me

**Comment by Bikash0007** [comment]
Please assign me this issue under hacktoberfest 2023.

**Comment by prashantcoding** [comment]
Hii please assign me this issue for hacktoberfest 2023
