### ISSUE TITLE
UI Improvement [Hacktoberfest]

### ISSUE THREAD

**Issue by AkashM398** [Ishaan28malik/Hacktoberfest-2024#195]
**Improve the UI [Hacktoberfest 2019]**

**Would you like to work on this Project?**
yes

_UI design link will be submitted soon!!_

**Comment by JHeroGR** [comment]
I would like to collaborate on this part of the project too so I can improve my UI skills.

**Comment by AkashM398** [comment]
> I would like to collaborate on this part of the project too so I can improve my UI skills.

Sure you can collaborate!! hope the issue will be accepted

**Comment by Ishaan28malik** [comment]
Yup U are free to do it and I already merged that PR.

**Comment by ghost** [comment]
Can i create a new icons ? i'm graphist

**Comment by Ishaan28malik** [comment]
@72y9op sure But try to switch here https://github.com/Ishaan28malik/Get-Dev-Resources , this needs help.
