### ISSUE TITLE
Update the png files.

### ISSUE THREAD

**Issue by Ishaan28malik** [Ishaan28malik/Hacktoberfest-2024#272]
Make sure that all the png files go-to a single folder instead of separate input.

**Comment by elissavetv** [comment]
Hi! I would like to work on it.

**Comment by elissavetv** [comment]
I am looking at the png files in the directory in my editor, I just don't understand what the issue precisely is. Do you just want all the png files in one folder? As in to make one folder in the directory for them?

**Comment by Ishaan28malik** [comment]
Yup u got it right @elissavetv

**Comment by elissavetv** [comment]
Awesome! Doing it now :D

**Comment by Ishaan28malik** [comment]
@elissavetv Seems like @Kameramann23 has fixed this.

**Comment by elissavetv** [comment]
Oh ok :( Is there anything else I can work on?

**Comment by Ishaan28malik** [comment]
Oh yes @elissavetv I am gonna update the issues. Please keep a check on them and also you can try the existing issues.
