### ISSUE TITLE
Working for a better UI and design.

### ISSUE THREAD

**Issue by Ishaan28malik** [Ishaan28malik/Hacktoberfest-2024#276]
Enhance the design and UI of the index.html and adding any new Javascript or CSS are welcome unless you have made them yourselves.

**Comment by danielharvilik** [comment]
Hey,is this still available for contribution?

**Comment by Ishaan28malik** [comment]
Hey @danielharvilik 
Yup it is open for contributions.

**Comment by danielharvilik** [comment]
Do you have specific enhancment in mind? Bootstrap adding three.js animation or else ?

**Comment by Ishaan28malik** [comment]
Bootstrap adding three.js animation looks good to me 
@danielharvilik

**Comment by danielharvilik** [comment]
can you assign me that one ?

**Comment by Ishaan28malik** [comment]
Yup sure @danielharvilik

**Comment by UPstartDeveloper** [comment]
Hello @Ishaan28malik, I am new to this repo and I notice that the index.html page is a little crowded at the top. Is it okay if I work on making sure all the people introductions show, maybe even moving it to the bottom of the page?
[UPDATE] Please review the PR I just opened, I moved the entire list of contributors (with the links to each of their GiHub profiles) inside of the footer div at the bottom of index.html.

**Comment by Ishaan28malik** [comment]
Ok @UPstartDeveloper thanks for the contribution , let me have a look.

**Comment by Sayan-dev** [comment]
i would like to contribute

**Comment by Ishaan28malik** [comment]
@Sayan-dev Go ahead
