### ISSUE TITLE
Adding new organsiation name to the Readme

### ISSUE THREAD

**Issue by Ishaan28malik** [Ishaan28malik/Hacktoberfest-2024#7]
U can add new names of open source organisations to the readme file

**Comment by Ishaan28malik** [comment]
@jmannfeld ok thanks can u pls explain it a little bit and yes pls do follow me and star the repository

**Comment by orestotel** [comment]
#34 added four organisation names

**Comment by Ishaan28malik** [comment]
ok cool

**Comment by Ishaan28malik** [comment]
@orestotel pls follow me and also star this repo

**Comment by tanvibattu** [comment]
#274 added new organisation name to readme file

**Comment by Ishaan28malik** [comment]
@tanvibattu Good that was merged, thanks  for contributing.

**Comment by vatsalanarang** [comment]
#279 added a new organisation name to readme file.

**Comment by Ishaan28malik** [comment]
@vatsalanarang that's great, thanks for contributing.

**Comment by CAT-ID** [comment]
#285 added a new organisation name to readme file.

**Comment by Ishaan28malik** [comment]
@CAT-ID Yup it just got merged thanks for your contribution.

**Comment by theinfosecguy** [comment]
#384 I've made a PR, have a look @Ishaan28malik

**Comment by hp77-creator** [comment]
###35 I added a new organisation.

**Comment by Ishaan28malik** [comment]
@hp77-creator I have merged it, thanks for contributing.

**Comment by Ishaan28malik** [comment]
@kmalik31 thanks for your contribution.

**Comment by santos-jadson** [comment]
Hello, I added a translation of the Readme file to portuguese. Please have a look at my PR #672

**Comment by Ishaan28malik** [comment]
@Jadson1197 thanks for contributing. it's already merged.

**Comment by KerinPithawala** [comment]
Added 2 new organisation name to the Readme. Please review  pr #958

**Comment by whtssub** [comment]
Hello, @Ishaan28malik  I've added new organizations to the list. PR #963. I hope someone finds it useful.

**Comment by Ameenrehman** [comment]
hello, @Ishaan28malik  i have added a new organization to the list.PR #981.if any changes please let me know.Thanks

**Comment by ChiragSaxena5437** [comment]
Hi, @Ishaan28malik  I have added InfraCloud in the list of companies offering swags please review PR #1024

**Comment by Ishaan28malik** [comment]
> Added 2 new organisation name to the Readme. Please review pr #958

Great

**Comment by Ishaan28malik** [comment]
> Hello, @Ishaan28malik I've added new organizations to the list. PR #963. I hope someone finds it useful.

Awesome
