### ISSUE TITLE
Adding Deployment 

### ISSUE THREAD

**Issue by Ishaan28malik** [Ishaan28malik/Hacktoberfest-2024#911]
**Deploying the web app **
Either Github Pages or Heroku

**Any other suggestions ?**
Are welcome to try

**Comment by Jating73** [comment]
Both are Best But I prefer Github as it provides an SSL certificate and free web hosting lifetime and even you can add your own domain name too if you buy from GoDaddy

**Comment by vipul0425** [comment]
you can have a good hosting and domain with ssl via github education plan for free if you are a college studend! must try!

**Comment by Ishaan28malik** [comment]
@vipul0425 @Jating73 will update and deploying it soon.
But once the web app is ready would anyone of you deploy that?

**Comment by altafshaikh** [comment]
may i know which type of app you want to deploy...static or dynamic website??

**Comment by elijahcruz12** [comment]
If you are looking to deploy a static site (eg. HTML, CSS, JavaScript), then Github Pages is the way to go. If you are using any server side scripting languages (eg. PHP, Ruby, Python), or using Node.JS, then you would need to deploy using another service like Heroku. Note though that even though Heroku does have a free plan, it is recommended to only use the free plan for Development, and instead using a paid version for a Production Deployment. Github Pages is free to use completely though.

**Comment by Ishaan28malik** [comment]
> may i know which type of app you want to deploy...static or dynamic website??

Dynamic

**Comment by GhostUser** [comment]
You can deploy on heroku, but you it offers only limited(550) hours per month without card details.
