### ISSUE TITLE
Add resources for Software testing

### ISSUE THREAD

**Issue by gfda** [Ishaan28malik/Hacktoberfest-2024#998]
Would it be a good idea to create a resource for software testing?

I would like to contribute to that.

**Comment by Ishaan28malik** [comment]
Sure @gfda

**Comment by gfda** [comment]
Create a folder and a file for testing automation.
#1014

**Comment by Raj-Banerjee** [comment]
What is the issue here?

**Comment by gfda** [comment]
Hello @Raj-Banerjee 
It's to adding content about SW testing on resources.

**Comment by Christine-Pinto** [comment]
What kind of content do you have in mind @gfda ? Most popular UI testing frameworks or testing communities?

**Comment by gfda** [comment]
Hi @ChrisZie 
I was thinking about sharing content like online courses, blogs, youtube channels... All around tests, communities are also welcome.

**Comment by Christine-Pinto** [comment]
That sounds good. I would like to do that. @gfda Should I wait with the fork until your PR is merged?

**Comment by gfda** [comment]
The PR will create a folder and a file, so it is best to wait for the merge to work on it.

But feel free to do that now, if you want. :)

**Comment by Ishaan28malik** [comment]
@ChrisZie & @gfda you both go ahead and make separate PRs or work out together.
But I would suggest to have a look at new Projects in my Project list , maybe You can help there.
